# Generated by Django 3.1.3 on 2021-02-02 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210202_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockholding',
            name='buying_value',
        ),
    ]
