# Generated by Django 3.1.3 on 2021-02-02 12:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_stockholding_buying_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockholding',
            name='buying_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), blank=True, size=None), blank=True, default=0, size=None),
            preserve_default=False,
        ),
    ]
