# Generated by Django 3.1.3 on 2021-02-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210202_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockholding',
            name='buying_value',
            field=models.JSONField(default=list),
        ),
    ]
