# Generated by Django 3.1.3 on 2021-02-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210202_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockholding',
            name='average_cost',
            field=models.FloatField(default=0),
        ),
    ]
