# Generated by Django 3.1.3 on 2021-02-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210202_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockholding',
            name='net_change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
