# Generated by Django 3.1.3 on 2021-02-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210202_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockholding',
            name='last_trading_price',
        ),
        migrations.AddField(
            model_name='stockholding',
            name='_last_trading_price',
            field=models.FloatField(default=0),
        ),
    ]
