# Generated by Django 3.1.3 on 2021-02-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_stockholding_company_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='total_investment',
            field=models.FloatField(default=0),
        ),
    ]
