# Generated by Django 3.1.3 on 2021-02-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_portfolio_total_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockholding',
            name='sector',
            field=models.CharField(default='', max_length=50),
        ),
    ]
