# Generated by Django 3.1.3 on 2021-03-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskprofile',
            name='age',
            field=models.CharField(default='under-30', max_length=30),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='annual_take_home_income',
            field=models.CharField(default='2-5-lakh', max_length=30),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='category',
            field=models.CharField(default='Conservative', max_length=30),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='critical_situation_response',
            field=models.CharField(default='average-out', max_length=30),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='current_life_stage',
            field=models.CharField(default='single', max_length=30),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='emergency_funds',
            field=models.CharField(default='no-emergency-fund', max_length=30),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='expected_return_rate',
            field=models.CharField(default='12-percent', max_length=30),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='high_reture_high_risk',
            field=models.CharField(default='disagree', max_length=30),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='investment_familiarity',
            field=models.CharField(default='somewhat-familiar', max_length=30),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='investment_length',
            field=models.CharField(default='3-5-years', max_length=30),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='investment_percentage',
            field=models.CharField(default='0-10-percent', max_length=30),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='keep_capital_safe',
            field=models.CharField(default='agree', max_length=30),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='work_status',
            field=models.CharField(default='is-secure', max_length=30),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='worry_if_fall_percentage',
            field=models.CharField(default='less-5-percent', max_length=30),
        ),
    ]
